#!/usr/bin/env bun

import { exec } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";
import type { RegistryItem } from "shadcn/schema";
import { fixImport, getFileTarget } from "@/lib/registry";
import { registry } from "@/registry";
import { BASE_STYLE_DIR, STYLES } from "@/registry/styles";

async function buildRegistryIndex() {
  let index = `
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles =
      item.files?.map(
        (file: (typeof item.files)[number]) =>
          `src/registry/bases/base/${file.path}`
      ) ?? [];
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/bases/base/${item.files[0].path}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${(item as Record<string, unknown>).description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file: (typeof item.files)[number]) => {
      const filePath = `src/registry/bases/base/${typeof file === "string" ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify((item as Record<string, unknown>).categories)},
    meta: ${JSON.stringify((item as Record<string, unknown>).meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  rimraf.sync(path.join(process.cwd(), "src/registry/__index__.tsx"));
  await fs.writeFile(
    path.join(process.cwd(), "src/registry/__index__.tsx"),
    index
  );
}

async function resolveStyleSourceRel(style: string, filePath: string) {
  const overrideRel = `src/registry/${style}/${filePath}`;
  try {
    await fs.access(path.join(process.cwd(), overrideRel));
    return overrideRel; // per-style override exists
  } catch {
    return `src/registry/${BASE_STYLE_DIR}/${filePath}`; // fall back to default/
  }
}

async function buildStyleRegistryJson(style: string) {
  const fixedRegistry = {
    ...registry,
    items: await Promise.all(
      registry.items.map(async (item: RegistryItem) => {
        const files = await Promise.all(
          (item.files || []).map(async (file) => {
            const filePath = await resolveStyleSourceRel(style, file.path);
            const resolvedPath = path.isAbsolute(filePath)
              ? filePath
              : path.join(process.cwd(), filePath);

            let content: string | undefined;
            try {
              const rawContent = await fs.readFile(resolvedPath, "utf-8");
              content = fixImport(rawContent);
            } catch (error) {
              console.warn(
                `Warning: Could not read file ${resolvedPath}:`,
                error
              );
            }

            const target = getFileTarget({
              path: file.path,
              type: file.type,
              target: file.target,
            });

            return {
              ...file,
              path: filePath,
              target,
              ...(content !== undefined && { content }),
            };
          })
        );

        return {
          ...item,
          files,
        };
      })
    ),
  };

  const registryFile = path.join(process.cwd(), `registry.${style}.json`);
  rimraf.sync(registryFile);
  await fs.writeFile(registryFile, JSON.stringify(fixedRegistry, null, 2));

  const publicRStyleDir = path.join(process.cwd(), `public/r/${style}`);
  await fs.mkdir(publicRStyleDir, { recursive: true });
  await fs.cp(registryFile, path.join(publicRStyleDir, "registry.json"), {
    recursive: true,
  });

  return registryFile;
}

async function buildStyleRegistry(style: string) {
  return await new Promise<void>((resolve, reject) => {
    const child = exec(
      `bunx shadcn build registry.${style}.json --output public/r/${style}`
    );

    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

try {
  console.log("🧹 Cleaning public/r directory...");
  const publicRPath = path.join(process.cwd(), "public/r");
  rimraf.sync(publicRPath);
  console.log("✅ Cleaned public/r directory");

  console.log("🗂️ Building src/registry/__index__.tsx...");
  await buildRegistryIndex();

  const tempFiles: string[] = [];

  for (const { name: style } of STYLES) {
    console.log(`💅 Building registry for style: ${style}...`);
    const tempFile = await buildStyleRegistryJson(style);
    tempFiles.push(tempFile);

    console.log(`🏗️ Building registry output for style: ${style}...`);
    await buildStyleRegistry(style);
  }

  // Clean up temporary per-style registry JSON files
  for (const tempFile of tempFiles) {
    rimraf.sync(tempFile);
  }

  console.log("✅ Registry build completed successfully!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
