
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "ui": {
    name: "ui",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/transport","@audio/sortable-list"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "transport": {
    name: "transport",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/bases/base/ui/audio/elements/transport.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/elements/transport.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list": {
    name: "sortable-list",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@shadcn/button"],
    files: [{
      path: "src/registry/bases/base/ui/sortable-list.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/sortable-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "knob": {
    name: "knob",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/bases/base/ui/audio/elements/knob.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/elements/knob.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fader": {
    name: "fader",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/bases/base/ui/audio/elements/fader.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/elements/fader.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "xypad": {
    name: "xypad",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/bases/base/ui/audio/elements/xypad.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/elements/xypad.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "player-demo": {
    name: "player-demo",
    description: "Audio player demo",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-queue-demo": {
    name: "player-queue-demo",
    description: "Audio player with queue demo",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-queue-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-queue-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "player-variant-demo": {
    name: "player-variant-demo",
    description: "AudioPlayer variant options (default, outline, ghost)",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-variant-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-variant-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-size-demo": {
    name: "player-size-demo",
    description: "AudioPlayer size options (sm, default, lg)",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-size-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-size-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-stacked-demo": {
    name: "player-stacked-demo",
    description: "Audio player with stacked layout",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-stacked-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-stacked-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-queue-shuffle-repeat-demo": {
    name: "player-queue-shuffle-repeat-demo",
    description: "Minimal queue with shuffle and repeat controls",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-queue-shuffle-repeat-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-queue-shuffle-repeat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "player-queue-preferences-demo": {
    name: "player-queue-preferences-demo",
    description: "Minimal queue with preferences dropdown",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-queue-preferences-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-queue-preferences-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "player-queue-simple-demo": {
    name: "player-queue-simple-demo",
    description: "Stacked player with queue and preferences",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-queue-simple-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-queue-simple-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "player-queue-all-controls-demo": {
    name: "player-queue-all-controls-demo",
    description: "Queue with all controls (shuffle, repeat, preferences)",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-queue-all-controls-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-queue-all-controls-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "player-track-demo": {
    name: "player-track-demo",
    description: "Minimal track component example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-track-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-track-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "player-track-list-demo": {
    name: "player-track-list-demo",
    description: "Track list with selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-track-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-track-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "player-track-list-grid-demo": {
    name: "player-track-list-grid-demo",
    description: "Track list with grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-track-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-track-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","grid"],
    meta: undefined,
  },
  "player-track-sortable-list-demo": {
    name: "player-track-sortable-list-demo",
    description: "Track list with sortable selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-track-sortable-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-track-sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable"],
    meta: undefined,
  },
  "player-track-sortable-list-grid-demo": {
    name: "player-track-sortable-list-grid-demo",
    description: "Track list with sortable selection and grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-track-sortable-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-track-sortable-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable","grid"],
    meta: undefined,
  },
  "transport-demo": {
    name: "transport-demo",
    description: "Transport timeline with buffered range example",
    type: "registry:example",
    registryDependencies: ["@audio/transport"],
    files: [{
      path: "src/registry/bases/base/examples/transport-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/transport-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["transport","ui"],
    meta: undefined,
  },
  "sortable-list-demo": {
    name: "sortable-list-demo",
    description: "Sortable list component examples",
    type: "registry:example",
    registryDependencies: ["@audio/sortable-list"],
    files: [{
      path: "src/registry/bases/base/examples/sortable-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["sortable-list","ui"],
    meta: undefined,
  },
  "player-playback-speed-demo": {
    name: "player-playback-speed-demo",
    description: "Playback speed component example",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/examples/player-playback-speed-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/player-playback-speed-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["playback-speed"],
    meta: undefined,
  },
  "fader-vertical-demo": {
    name: "fader-vertical-demo",
    description: "Vertical fader",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/bases/base/examples/fader-vertical-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/fader-vertical-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-horizontal-demo": {
    name: "fader-horizontal-demo",
    description: "Fader component example with horizontal orientation",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/bases/base/examples/fader-horizontal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/fader-horizontal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-size-variants-demo": {
    name: "fader-size-variants-demo",
    description: "Fader size variants (sm, default, lg)",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/bases/base/examples/fader-size-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/fader-size-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-thumb-marks-variants-demo": {
    name: "fader-thumb-marks-variants-demo",
    description: "Fader thumb marks variants (off, 1, 4)",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/bases/base/examples/fader-thumb-marks-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/fader-thumb-marks-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "knob-demo": {
    name: "knob-demo",
    description: "Knob component example",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-disabled-demo": {
    name: "knob-disabled-demo",
    description: "Knob disabled vs enabled comparison",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-disabled-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-disabled-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-size-variants-demo": {
    name: "knob-size-variants-demo",
    description: "Knob component example with size variants",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-size-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-size-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-fine-step-demo": {
    name: "knob-fine-step-demo",
    description: "Knob with fine-grained step control (0.01)",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-fine-step-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-fine-step-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-filter-control-demo": {
    name: "knob-filter-control-demo",
    description: "Knob component example with filter control",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-filter-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-filter-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-change-vs-commit-demo": {
    name: "knob-change-vs-commit-demo",
    description: "Knob live value vs committed value callbacks",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-change-vs-commit-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-change-vs-commit-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-arc-and-anchor-demo": {
    name: "knob-arc-and-anchor-demo",
    description: "Knob value arc (rail + highlight) and optional anchor range",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-arc-and-anchor-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-arc-and-anchor-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-circular-arc-demo": {
    name: "knob-circular-arc-demo",
    description: "Knob with default arc pointer mapping and live value",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-circular-arc-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-circular-arc-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-double-tap-reset-demo": {
    name: "knob-double-tap-reset-demo",
    description: "Knob double-tap / double-click reset to defaultValue",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-double-tap-reset-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-double-tap-reset-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-revolution-drag-demo": {
    name: "knob-revolution-drag-demo",
    description: "Knob with revolution (360°) drag sensitivity",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-revolution-drag-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-revolution-drag-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-vertical-drag-demo": {
    name: "knob-vertical-drag-demo",
    description: "Knob with vertical fader-style pan via dragOptions.verticalPanEnabled",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/bases/base/examples/knob-vertical-drag-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/knob-vertical-drag-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "xypad-live-value-demo": {
    name: "xypad-live-value-demo",
    description: "XYPad with live x/y readout",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-live-value-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-live-value-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-size-sm-demo": {
    name: "xypad-size-sm-demo",
    description: "XYPad size small example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-size-sm-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-size-sm-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-size-default-demo": {
    name: "xypad-size-default-demo",
    description: "XYPad size default example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-size-default-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-size-default-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-size-lg-demo": {
    name: "xypad-size-lg-demo",
    description: "XYPad size large example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-size-lg-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-size-lg-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-size-xl-demo": {
    name: "xypad-size-xl-demo",
    description: "XYPad size extra large example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-size-xl-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-size-xl-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-disabled-demo": {
    name: "xypad-disabled-demo",
    description: "XYPad disabled state example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-disabled-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-disabled-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-format-value-demo": {
    name: "xypad-format-value-demo",
    description: "XYPad component example with formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-format-value-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-format-value-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-bipolar-range-demo": {
    name: "xypad-bipolar-range-demo",
    description: "XYPad with bipolar pan/mix style ranges",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-bipolar-range-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-bipolar-range-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-change-vs-commit-demo": {
    name: "xypad-change-vs-commit-demo",
    description: "XYPad live value vs committed value callbacks",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-change-vs-commit-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-change-vs-commit-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-hide-value-demo": {
    name: "xypad-hide-value-demo",
    description: "XYPad component example with hidden value",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/examples/xypad-hide-value-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/examples/xypad-hide-value-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "html": {
    name: "html",
    description: "HTML Audio Lib",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "src/registry/bases/base/lib/html-audio.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/lib/html-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","html-audio"],
    meta: undefined,
  },
  "web": {
    name: "web",
    description: "Web Audio Lib",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "src/registry/bases/base/lib/web-audio.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/lib/web-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","web-audio"],
    meta: undefined,
  },
  "store": {
    name: "store",
    description: "Audio store",
    type: "registry:lib",
    registryDependencies: ["@audio/html"],
    files: [{
      path: "src/registry/bases/base/lib/audio-store.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/lib/audio-store.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","store"],
    meta: undefined,
  },
  "player": {
    name: "player",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio","@audio/fader","@audio/transport","@audio/sortable-list","@shadcn/button","@shadcn/dropdown-menu","@shadcn/spinner","@shadcn/tooltip","@shadcn/command","@shadcn/dialog","@shadcn/toggle","@shadcn/badge","@shadcn/empty","@shadcn/avatar","@shadcn/item","@shadcn/scroll-area"],
    files: [{
      path: "src/registry/bases/base/ui/audio/player.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "src/registry/bases/base/hooks/use-audio-provider.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "channel-strip": {
    name: "channel-strip",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/bases/base/ui/audio/elements/channel-strip.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/ui/audio/elements/channel-strip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "block-pocket-synth": {
    name: "block-pocket-synth",
    description: "Pocket synth with oscillator, filter, and XY pad",
    type: "registry:block",
    registryDependencies: ["@audio/use-audio","@audio/fader","@audio/xypad","@shadcn/toggle-group"],
    files: [{
      path: "src/registry/bases/base/blocks/block-pocket-synth.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-pocket-synth.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["synth","xypad"],
    meta: undefined,
  },
  "block-wave-shaper": {
    name: "block-wave-shaper",
    description: "Wave shaper synth with distortion, tone, and detune controls",
    type: "registry:block",
    registryDependencies: ["@audio/use-audio","@audio/fader","@audio/xypad","@audio/knob","@shadcn/toggle-group"],
    files: [{
      path: "src/registry/bases/base/blocks/block-wave-shaper.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-wave-shaper.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["synth","xypad"],
    meta: undefined,
  },
  "block-player": {
    name: "block-player",
    description: "Audio player",
    type: "registry:block",
    registryDependencies: ["@audio/player","@audio/store","@audio/html"],
    files: [{
      path: "src/registry/bases/base/blocks/block-player.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "block-player-widget": {
    name: "block-player-widget",
    description: "Audio player with track list",
    type: "registry:block",
    registryDependencies: ["@audio/player","@audio/store","@audio/html"],
    files: [{
      path: "src/registry/bases/base/blocks/block-player-widget.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-player-widget.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","widget"],
    meta: undefined,
  },
  "block-queue": {
    name: "block-queue",
    description: "Queue controls",
    type: "registry:block",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/bases/base/blocks/block-queue.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-queue.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue","ui"],
    meta: undefined,
  },
  "block-channel-strip-transport-vertical": {
    name: "block-channel-strip-transport-vertical",
    description: "Channel strip with transport seek bar in vertical orientation",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/transport"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-transport-vertical.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-transport-vertical.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","transport"],
    meta: undefined,
  },
  "block-channel-strip-transport": {
    name: "block-channel-strip-transport",
    description: "Channel strip with transport seek bar in horizontal orientation",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/transport"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-transport.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-transport.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","transport"],
    meta: undefined,
  },
  "block-channel-strip": {
    name: "block-channel-strip",
    description: "Channel strip with fader, header, and footer",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-horizontal": {
    name: "block-channel-strip-horizontal",
    description: "Channel strip with fader in horizontal orientation",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-horizontal.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-horizontal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-fader": {
    name: "block-channel-strip-fader",
    description: "Channel strip with a minimal fader section",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-fader.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-fader.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-fader-gain-db": {
    name: "block-channel-strip-fader-gain-db",
    description: "Channel strip with bipolar gain fader (-60 dB to +6 dB)",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-fader-gain-db.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-fader-gain-db.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-fader-multi": {
    name: "block-channel-strip-fader-multi",
    description: "Multiple fader channel strips in a row",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-fader-multi.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-fader-multi.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader"],
    meta: undefined,
  },
  "block-channel-strip-knob-multi": {
    name: "block-channel-strip-knob-multi",
    description: "Multiple knob channel strips in a row",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-knob-multi.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-knob-multi.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","knob"],
    meta: undefined,
  },
  "block-channel-strip-fader-horizontal": {
    name: "block-channel-strip-fader-horizontal",
    description: "Channel strip with a minimal fader section in horizontal orientation",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-fader-horizontal.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-fader-horizontal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-fader-slider": {
    name: "block-channel-strip-fader-slider",
    description: "Channel strip with horizontal fader and inline label",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/fader"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-fader-slider.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-fader-slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","fader","ui"],
    meta: undefined,
  },
  "block-channel-strip-knob-level": {
    name: "block-channel-strip-knob-level",
    description: "Channel strip with a level knob",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-knob-level.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-knob-level.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","knob","ui"],
    meta: undefined,
  },
  "block-channel-strip-knob-macro": {
    name: "block-channel-strip-knob-macro",
    description: "Channel strip with an oversized macro knob",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-knob-macro.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-knob-macro.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","knob","ui"],
    meta: undefined,
  },
  "block-channel-strip-knob-pan": {
    name: "block-channel-strip-knob-pan",
    description: "Channel strip with a bipolar pan knob",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-knob-pan.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-knob-pan.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","knob","ui"],
    meta: undefined,
  },
  "block-channel-strip-knob-pan-width": {
    name: "block-channel-strip-knob-pan-width",
    description: "Channel strip with pan and width knobs in a row",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-knob-pan-width.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-knob-pan-width.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","knob","ui"],
    meta: undefined,
  },
  "block-channel-strip-xypad-filter": {
    name: "block-channel-strip-xypad-filter",
    description: "Channel strip with an XY filter pad",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/xypad"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-xypad-filter.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-xypad-filter.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","xypad","ui"],
    meta: undefined,
  },
  "block-channel-strip-xypad-reverb": {
    name: "block-channel-strip-xypad-reverb",
    description: "Channel strip with XY spatial pad and wet knob",
    type: "registry:block",
    registryDependencies: ["@audio/channel-strip","@audio/xypad","@audio/knob"],
    files: [{
      path: "src/registry/bases/base/blocks/block-channel-strip-xypad-reverb.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/blocks/block-channel-strip-xypad-reverb.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["channel-strip","xypad","ui"],
    meta: undefined,
  },
  "hooks": {
    name: "hooks",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/use-audio","@audio/use-sound"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "use-audio": {
    name: "use-audio",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/html","@audio/web"],
    files: [{
      path: "src/registry/bases/base/hooks/use-audio.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/hooks/use-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: undefined,
  },
  "use-sound": {
    name: "use-sound",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/use-audio"],
    files: [{
      path: "src/registry/bases/base/hooks/use-sound.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bases/base/hooks/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio","sound"],
    meta: undefined,
  },
  "theme-neutral": {
    name: "theme-neutral",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-stone": {
    name: "theme-stone",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-zinc": {
    name: "theme-zinc",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-mauve": {
    name: "theme-mauve",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-olive": {
    name: "theme-olive",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-mist": {
    name: "theme-mist",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-taupe": {
    name: "theme-taupe",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-amber": {
    name: "theme-amber",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-blue": {
    name: "theme-blue",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-cyan": {
    name: "theme-cyan",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-emerald": {
    name: "theme-emerald",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-fuchsia": {
    name: "theme-fuchsia",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-green": {
    name: "theme-green",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-indigo": {
    name: "theme-indigo",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-lime": {
    name: "theme-lime",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-orange": {
    name: "theme-orange",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-pink": {
    name: "theme-pink",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-purple": {
    name: "theme-purple",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-red": {
    name: "theme-red",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-rose": {
    name: "theme-rose",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-sky": {
    name: "theme-sky",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-teal": {
    name: "theme-teal",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-violet": {
    name: "theme-violet",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-yellow": {
    name: "theme-yellow",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  }