
/** biome-ignore-all lint/suspicious/noExplicitAny: we use any to avoid type errors */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react" 

export const Index: Record<string, any> = {
  "player": {
    name: "player",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio","@audio/provider","@audio/slider","@shadcn/empty","@shadcn/button","@shadcn/dialog","@shadcn/dropdown-menu","@shadcn/input","@shadcn/item","@shadcn/scroll-area","@shadcn/toggle","@shadcn/tooltip"],
    files: [{
      path: "src/registry/default/ui/audio/player.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "provider": {
    name: "provider",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio"],
    files: [{
      path: "src/registry/default/ui/audio/provider.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/provider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "queue": {
    name: "queue",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio","@audio/track","@audio/provider","@shadcn/empty","@shadcn/button","@shadcn/command","@shadcn/dialog","@shadcn/dropdown-menu","@shadcn/input","@shadcn/item","@shadcn/scroll-area","@shadcn/toggle","@shadcn/tooltip"],
    files: [{
      path: "src/registry/default/ui/audio/queue.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/queue.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "track": {
    name: "track",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio","@audio/sortable-list","@audio/provider","@shadcn/badge","@shadcn/empty","@shadcn/avatar","@shadcn/button","@shadcn/item","@shadcn/scroll-area"],
    files: [{
      path: "src/registry/default/ui/audio/track.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/track.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "playback-speed": {
    name: "playback-speed",
    description: "",
    type: "registry:component",
    registryDependencies: ["@audio/store","@audio/html","@audio/use-audio","@shadcn/button","@shadcn/dropdown-menu","@shadcn/tooltip"],
    files: [{
      path: "src/registry/default/ui/audio/playback-speed.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/playback-speed.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ui": {
    name: "ui",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@audio/slider","@audio/sortable-list"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "slider": {
    name: "slider",
    description: "",
    type: "registry:ui",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/ui/slider.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/slider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sortable-list": {
    name: "sortable-list",
    description: "",
    type: "registry:ui",
    registryDependencies: ["@shadcn/button"],
    files: [{
      path: "src/registry/default/ui/sortable-list.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/sortable-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "knob": {
    name: "knob",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/audio/elements/knob.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/elements/knob.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "fader": {
    name: "fader",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/audio/elements/fader.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/elements/fader.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "xypad": {
    name: "xypad",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/default/ui/audio/elements/xypad.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/ui/audio/elements/xypad.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "player-demo": {
    name: "player-demo",
    description: "Audio player demo",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/default/examples/player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "player-queue-demo": {
    name: "player-queue-demo",
    description: "Audio player with queue demo",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/player-queue-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-queue-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "player-stacked-demo": {
    name: "player-stacked-demo",
    description: "Audio player with stacked layout",
    type: "registry:example",
    registryDependencies: ["@audio/player"],
    files: [{
      path: "src/registry/default/examples/player-stacked-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/player-stacked-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player"],
    meta: undefined,
  },
  "queue-shuffle-repeat-demo": {
    name: "queue-shuffle-repeat-demo",
    description: "Minimal queue with shuffle and repeat controls",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-shuffle-repeat-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-shuffle-repeat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "queue-preferences-demo": {
    name: "queue-preferences-demo",
    description: "Minimal queue with preferences dropdown",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-preferences-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-preferences-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "queue-all-controls-demo": {
    name: "queue-all-controls-demo",
    description: "Queue with all controls (shuffle, repeat, preferences)",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/queue"],
    files: [{
      path: "src/registry/default/examples/queue-all-controls-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/queue-all-controls-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["queue"],
    meta: undefined,
  },
  "track-demo": {
    name: "track-demo",
    description: "Minimal track component example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "track-list-demo": {
    name: "track-list-demo",
    description: "Track list with selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track"],
    meta: undefined,
  },
  "track-list-grid-demo": {
    name: "track-list-grid-demo",
    description: "Track list with grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","grid"],
    meta: undefined,
  },
  "track-sortable-list-demo": {
    name: "track-sortable-list-demo",
    description: "Track list with sortable selection example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-sortable-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable"],
    meta: undefined,
  },
  "track-sortable-list-grid-demo": {
    name: "track-sortable-list-grid-demo",
    description: "Track list with sortable selection and grid layout example",
    type: "registry:example",
    registryDependencies: ["@audio/player","@audio/track"],
    files: [{
      path: "src/registry/default/examples/track-sortable-list-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/track-sortable-list-grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["track","sortable","grid"],
    meta: undefined,
  },
  "slider-demo": {
    name: "slider-demo",
    description: "Slider component examples",
    type: "registry:example",
    registryDependencies: ["@audio/slider"],
    files: [{
      path: "src/registry/default/examples/slider-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/slider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["slider","ui"],
    meta: undefined,
  },
  "sortable-list-demo": {
    name: "sortable-list-demo",
    description: "Sortable list component examples",
    type: "registry:example",
    registryDependencies: ["@audio/sortable-list"],
    files: [{
      path: "src/registry/default/examples/sortable-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/sortable-list-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["sortable-list","ui"],
    meta: undefined,
  },
  "playback-speed-demo": {
    name: "playback-speed-demo",
    description: "Playback speed component example",
    type: "registry:example",
    registryDependencies: ["@audio/playback-speed","@audio/player"],
    files: [{
      path: "src/registry/default/examples/playback-speed-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/playback-speed-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["playback-speed"],
    meta: undefined,
  },
  "fader-demo": {
    name: "fader-demo",
    description: "Fader component example",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-horizontal-demo": {
    name: "fader-horizontal-demo",
    description: "Fader component example with horizontal orientation",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-horizontal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-horizontal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-no-thumb-marks-demo": {
    name: "fader-no-thumb-marks-demo",
    description: "Fader component example with no thumb marks",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-no-thumb-marks-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-no-thumb-marks-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-custom-thumb-marks-demo": {
    name: "fader-custom-thumb-marks-demo",
    description: "Fader component example with custom thumb marks",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-custom-thumb-marks-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-custom-thumb-marks-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-multiple-control-demo": {
    name: "fader-multiple-control-demo",
    description: "Fader component example with multiple controls",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-multiple-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-multiple-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "fader-volume-control-demo": {
    name: "fader-volume-control-demo",
    description: "Fader component example with volume control",
    type: "registry:example",
    registryDependencies: ["@audio/fader"],
    files: [{
      path: "src/registry/default/examples/fader-volume-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/fader-volume-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["fader"],
    meta: undefined,
  },
  "knob-demo": {
    name: "knob-demo",
    description: "Knob component example",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/default/examples/knob-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/knob-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-size-variants-demo": {
    name: "knob-size-variants-demo",
    description: "Knob component example with size variants",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/default/examples/knob-size-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/knob-size-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-filter-control-demo": {
    name: "knob-filter-control-demo",
    description: "Knob component example with filter control",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/default/examples/knob-filter-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/knob-filter-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "knob-multiple-control-demo": {
    name: "knob-multiple-control-demo",
    description: "Knob component example with multiple controls",
    type: "registry:example",
    registryDependencies: ["@audio/knob"],
    files: [{
      path: "src/registry/default/examples/knob-multiple-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/knob-multiple-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["knob"],
    meta: undefined,
  },
  "xypad-demo": {
    name: "xypad-demo",
    description: "XYPad component example",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/default/examples/xypad-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/xypad-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-format-value-demo": {
    name: "xypad-format-value-demo",
    description: "XYPad component example with formatted value",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/default/examples/xypad-format-value-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/xypad-format-value-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-hide-value-demo": {
    name: "xypad-hide-value-demo",
    description: "XYPad component example with hidden value",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/default/examples/xypad-hide-value-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/xypad-hide-value-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-filter-control-demo": {
    name: "xypad-filter-control-demo",
    description: "XYPad component example with filter control",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/default/examples/xypad-filter-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/xypad-filter-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "xypad-synthesizer-control-demo": {
    name: "xypad-synthesizer-control-demo",
    description: "XYPad component example with synthesizer control",
    type: "registry:example",
    registryDependencies: ["@audio/xypad"],
    files: [{
      path: "src/registry/default/examples/xypad-synthesizer-control-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/examples/xypad-synthesizer-control-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["xypad"],
    meta: undefined,
  },
  "theme-stone": {
    name: "theme-stone",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-zinc": {
    name: "theme-zinc",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-neutral": {
    name: "theme-neutral",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-gray": {
    name: "theme-gray",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "theme-slate": {
    name: "theme-slate",
    description: "",
    type: "registry:theme",
    registryDependencies: undefined,
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "particle-pocket-synth": {
    name: "particle-pocket-synth",
    description: "Pocket synth",
    type: "registry:block",
    registryDependencies: ["@audio/use-audio","@audio/fader","@audio/xypad","@shadcn/toggle-group"],
    files: [{
      path: "src/registry/default/particles/particle-pocket-synth.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-pocket-synth.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["synth"],
    meta: undefined,
  },
  "particle-wave-shaper": {
    name: "particle-wave-shaper",
    description: "Wave shaper",
    type: "registry:block",
    registryDependencies: ["@audio/use-audio","@audio/fader","@audio/xypad","@audio/knob","@shadcn/toggle-group"],
    files: [{
      path: "src/registry/default/particles/particle-wave-shaper.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-wave-shaper.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["synth"],
    meta: undefined,
  },
  "particle-player": {
    name: "particle-player",
    description: "Audio player",
    type: "registry:block",
    registryDependencies: ["@audio/player","@audio/queue","@audio/store","@audio/html"],
    files: [{
      path: "src/registry/default/particles/particle-player.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","queue"],
    meta: undefined,
  },
  "particle-player-widget": {
    name: "particle-player-widget",
    description: "Audio player widget",
    type: "registry:block",
    registryDependencies: ["@audio/provider","@audio/player","@audio/queue","@audio/track","@audio/store","@audio/html"],
    files: [{
      path: "src/registry/default/particles/particle-player-widget.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/particles/particle-player-widget.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["player","widget"],
    meta: undefined,
  },
  "hooks": {
    name: "hooks",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/use-audio","@audio/use-sound"],
    files: [undefined],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "use-audio": {
    name: "use-audio",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/html","@audio/web"],
    files: [{
      path: "src/registry/default/hooks/use-audio.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/hooks/use-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: undefined,
  },
  "use-sound": {
    name: "use-sound",
    description: "",
    type: "registry:hook",
    registryDependencies: ["@audio/use-audio"],
    files: [{
      path: "src/registry/default/hooks/use-sound.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/hooks/use-sound.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio","sound"],
    meta: undefined,
  },
  "html": {
    name: "html",
    description: "HTML Audio Lib",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/lib/html-audio.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/html-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","html-audio"],
    meta: undefined,
  },
  "web": {
    name: "web",
    description: "Web Audio Lib",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "src/registry/default/lib/web-audio.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/web-audio.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","web-audio"],
    meta: undefined,
  },
  "store": {
    name: "store",
    description: "Audio store",
    type: "registry:lib",
    registryDependencies: ["@audio/html"],
    files: [{
      path: "src/registry/default/lib/audio-store.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/lib/audio-store.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["lib","audio","store"],
    meta: undefined,
  },
  }