import type { Registry } from "shadcn/schema";

export const blocks: Registry["items"] = [
  {
    name: "block-pocket-synth",
    description: "Pocket synth",
    type: "registry:block",
    registryDependencies: [
      "@audio/use-audio",
      "@audio/fader",
      "@audio/xypad",
      "@shadcn/toggle-group",
    ],
    files: [{ path: "blocks/block-pocket-synth.tsx", type: "registry:block" }],
    categories: ["synth", "xypad"],
  },
  {
    name: "block-wave-shaper",
    description: "Wave shaper",
    type: "registry:block",
    registryDependencies: [
      "@audio/use-audio",
      "@audio/fader",
      "@audio/xypad",
      "@audio/knob",
      "@shadcn/toggle-group",
    ],
    files: [{ path: "blocks/block-wave-shaper.tsx", type: "registry:block" }],
    categories: ["synth", "xypad"],
  },
  {
    name: "block-player",
    description: "Audio player",
    type: "registry:block",
    registryDependencies: [
      "@audio/player",
      "@audio/queue",
      "@audio/store",
      "@audio/html",
    ],
    files: [{ path: "blocks/block-player.tsx", type: "registry:block" }],
    categories: ["player", "queue"],
  },
  {
    name: "block-player-widget",
    description: "Audio player widget",
    type: "registry:block",
    registryDependencies: [
      "@audio/provider",
      "@audio/player",
      "@audio/queue",
      "@audio/track",
      "@audio/store",
      "@audio/html",
    ],
    files: [{ path: "blocks/block-player-widget.tsx", type: "registry:block" }],
    categories: ["player", "widget"],
  },
  {
    name: "block-queue",
    description: "Queue controls",
    type: "registry:block",
    registryDependencies: ["@audio/player", "@audio/queue"],
    files: [{ path: "blocks/block-queue.tsx", type: "registry:block" }],
    categories: ["queue", "ui"],
  },
  {
    name: "block-level-knob",
    description: "Level knob",
    type: "registry:block",
    registryDependencies: ["@audio/knob"],
    files: [{ path: "blocks/block-level-knob.tsx", type: "registry:block" }],
    categories: ["knob", "ui"],
  },
  {
    name: "block-macro-knob",
    description: "Macro knob",
    type: "registry:block",
    registryDependencies: ["@audio/knob"],
    files: [{ path: "blocks/block-macro-knob.tsx", type: "registry:block" }],
    categories: ["knob", "ui"],
  },
  {
    name: "block-volume-slider",
    description: "Volume slider",
    type: "registry:block",
    registryDependencies: ["@audio/fader"],
    files: [{ path: "blocks/block-volume-slider.tsx", type: "registry:block" }],
    categories: ["fader", "ui"],
  },
  {
    name: "block-volume-inline",
    description: "Inline volume slider",
    type: "registry:block",
    registryDependencies: ["@audio/fader"],
    files: [{ path: "blocks/block-volume-inline.tsx", type: "registry:block" }],
    categories: ["fader", "ui"],
  },
  {
    name: "block-volume-strip",
    description: "Volume strip",
    type: "registry:block",
    registryDependencies: ["@audio/fader"],
    files: [{ path: "blocks/block-volume-strip.tsx", type: "registry:block" }],
    categories: ["fader", "ui"],
  },
  {
    name: "block-filter-pad",
    description: "Filter pad",
    type: "registry:block",
    registryDependencies: ["@audio/xypad"],
    files: [{ path: "blocks/block-filter-pad.tsx", type: "registry:block" }],
    categories: ["xypad", "ui"],
  },
  {
    name: "block-atmos-morph-pad",
    description: "Atmos morph pad",
    type: "registry:block",
    registryDependencies: ["@audio/xypad", "@audio/fader"],
    files: [
      { path: "blocks/block-atmos-morph-pad.tsx", type: "registry:block" },
    ],
    categories: ["xypad", "ui"],
  },
  {
    name: "block-transport",
    description: "Transport timeline",
    type: "registry:block",
    registryDependencies: ["@audio/transport"],
    files: [{ path: "blocks/block-transport.tsx", type: "registry:block" }],
    categories: ["transport", "ui"],
  },
  {
    name: "block-pan-knob",
    description: "Pan knob",
    type: "registry:block",
    registryDependencies: ["@audio/knob"],
    files: [{ path: "blocks/block-pan-knob.tsx", type: "registry:block" }],
    categories: ["knob", "ui"],
  },
  {
    name: "block-pan-width-controls",
    description: "Pan width controls",
    type: "registry:block",
    registryDependencies: ["@audio/knob"],
    files: [
      { path: "blocks/block-pan-width-controls.tsx", type: "registry:block" },
    ],
    categories: ["knob", "ui"],
  },
];
